Preparation du temoignage.
DuchessFrance/DuchessFrance.github.io pull request #108
Opened 2023-02-23 16:55 UTC by aHenryJard

# Bienvenue sur les contributions Duchess ! 🦄

## Contenu de la Pull Request

- Description: 

- Lien vers la github issue si il y a:

[Lien vers les consignes de contribution](https://github.com/DuchessFrance/DuchessFrance.github.io/blob/main/CONTRIBUTING.md)

2023-02-23 17:08 UTC, al2b commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Je ne peux m'empêcher de penser que si j'avais été un homme ma carrière serait plus avancée aujourd'hui, mon salaire supérieur et ma santé mentale bien meilleure.
❤️❤️

2023-02-23 17:51 UTC, P4uline commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Je suis fatiguée d’essayer de trouver ma voie dans une industrie qui fait tout pour me mettre des bâtons dans les roues, je suis fatiguée de voir mes collègues masculins cherchent à tricher pour fini
```suggestion
Je suis fatiguée d’essayer de trouver ma voie dans une industrie qui fait tout pour me mettre des bâtons dans les roues, je suis fatiguée de voir que mes collègues masculins cherchent à tricher pour finir au plus vite les formations “diversité et inclusion”.
```

2023-02-24 09:15 UTC, mbouquet77 requested changes

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2022/06/2022-06-20-mail-inapproprie.md
> +> **Note de la Core Team Duchess**: La personne qui a écrit ce blog a  souhaité le faire de façon anonyme, nous nous sommes attachées à retirer  les éléments permettant d’identifier d’une façon ou d’
```suggestion
> **Note de la Core Team Duchess**: La personne qui a écrit ce billet a souhaité le faire de façon anonyme, nous nous sommes attachées à retirer les éléments permettant d’identifier d’une façon ou d’une autre la  personne. Si vous pensez reconnaître la personne, nous vous serions reconnaissantes de garder cette information pour vous.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +| ![ Image d'une femme coincée sous un plafond de verre](/assets/2023/03/2023-03-08-stupeur-et-tremblements/plafond-de-verre.jpg){: width="300", height="300"} | J’ai heurté un mur il y a quelques moi
```suggestion
| ![ Image d'une femme coincée sous un plafond de verre](/assets/2023/03/2023-03-08-stupeur-et-tremblements/plafond-de-verre.jpg){: width="300", height="300"} | J’ai heurté un mur il y a quelques mois et depuis cette question revient sans cesse comme une rengaine: Trouverai-je un jour ma place dans cette industrie ? |
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +J’ai heurté un mur il y a quelques mois et depuis cette question revient sans cesse comme une rengaine: Trouverais-je un jour ma place dans cette industrie ? Je n’arrive pas à y répondre.
```suggestion
J’ai heurté un mur il y a quelques mois et depuis cette question revient sans cesse comme une rengaine: Trouverai-je un jour ma place dans cette industrie ? Je n’arrive pas à y répondre.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +**Moi j’étais toute contente: “Youpie, enfin une entreprise dans laquelle j’ai mes chances !”.**
```suggestion
**Moi j’étais toute contente: “Youpi, enfin une entreprise dans laquelle j’ai mes chances !”.**
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Les processus de promotion sont souvent annuels, ou bi annuel et je savais bien qu’il me fallait un peu de patience.
```suggestion
Les processus de promotion sont souvent annuels, ou biannuels et je savais bien qu’il me fallait un peu de patience.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Viens un jour de réunion générale ou tout d’un coup surgit un slide pour féliciter les personnes fraîchement promues et là, comme dirait Amélie Nothomb: **stupeur et tremblement** ! Ça me frappe immé
```suggestion
Vient un jour de réunion générale ou tout d’un coup surgit un slide pour féliciter les personnes fraîchement promues et là, comme dirait Amélie Nothomb: **stupeur et tremblement** ! Ça me frappe immédiatement: j’aurais dû être sur ce slide ! Que s’est-il passé ?
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Ils m’ont dénigrée auprès des managers sans que j’en sache rien, ils s’amusaient à changer des parties de l’application au dernier moment pour que la partie que je développe ne fonctionne plus lors d
```suggestion
Ils m’ont dénigrée auprès des managers sans que j’en sache rien, ils s’amusaient à changer des parties de l’application au dernier moment pour que la partie que je développais ne fonctionne plus lors des démonstrations.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Quand j'entrai dans la pièce où ils étaient pour discuter projet ils se taisaient et m’ignoraient.
```suggestion
Quand j'entrais dans la pièce où ils étaient pour discuter projet, ils se taisaient et m’ignoraient.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +J’ai mis plus d’un an à comprendre que le problème ce n’était pas moi, grâce à beaucoup de témoignages du genre “oui mais bon avec eux tu avais aucune chances, t’es une femme”.
```suggestion
J’ai mis plus d’un an à comprendre que le problème ce n’était pas moi, grâce à beaucoup de témoignages du genre “oui mais bon avec eux tu avais aucune chance, t’es une femme”.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Ça m'a peut-être fermé des opportunités, peut-être pas je ne saurais jamais.
```suggestion
Ça m'a peut-être fermé des opportunités, peut-être pas je ne saurai jamais.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Mais ça m’a mise sur le qui vive, un peu permanent.
```suggestion
Mais ça m’a mise sur le qui-vive un peu permanent.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Parmi les personnes promues, il y avait un homme avec qui le courant passait bien: ça tombe bien il venait d’être promu au niveau que je visait !
```suggestion
Parmi les personnes promues, il y avait un homme avec qui le courant passait bien : ça tombe bien il venait d’être promu au niveau que je visais !
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Après l’avoir félicité, je lui demande “Dis moi, quelles étapes tu as du faire pour ta promotion ?”.
```suggestion
Après l’avoir félicité, je lui demande “Dis moi, quelles étapes tu as dû suivre pour ta promotion ?”.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Sur ce, mon manager démissionne, je crois être la goutte qui a fait déborder le vase, mais je ne le saurais jamais.
```suggestion
Sur ce, mon manager démissionne, je crois être la goutte qui a fait déborder le vase, mais je ne le saurai jamais.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Je reste sans voix: “Impactée ??” Il m’explique qu’effectivement mon manager à proposé mon nom en fin de réunion, mais qu’ils n’avaient plus le temps et que de toute façon mon manager s’est braqué.
```suggestion
Je reste sans voix: “Impactée ??” Il m’explique qu’effectivement mon manager a proposé mon nom en fin de réunion, mais qu’ils n’avaient plus le temps et que de toute façon mon manager s’est braqué.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Il me dit vaguement que je manque de visibilité, ce à quoi je commence à lui exposer toutes les réalisations que j’ai faites, incluant des talk en public et enregistrés donc facilement consultables.
```suggestion
Il me dit vaguement que je manque de visibilité, ce à quoi je commence à lui exposer toutes les réalisations que j’ai faites, incluant des talks en public et enregistrés donc facilement consultables.
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +**Heureusement, j’avais commencé à chercher du soutien auprès de quelques Duchess, elles ont été formidables et m’ont beaucoup aidées, je les remercie vraiment très fort. 💖**
```suggestion
**Heureusement, j’avais commencé à chercher du soutien auprès de quelques Duchess, elles ont été formidables et m’ont beaucoup aidée, je les remercie vraiment très fort. 💖**
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Tout ça parce qu’un supérieur “ne le sens pas” ?
```suggestion
Tout ça parce qu’un supérieur “ne le sent pas” ?
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +![ Image d'une femme coincée sous un plafond de verre. La direction lui dit "Le plafond de verre c'est notre plancher, alors ne le nassez pas."](/assets/2023/03/2023-03-08-stupeur-et-tremblements/pla
```suggestion
![ Image d'une femme coincée sous un plafond de verre. La direction lui dit "Le plafond de verre c'est notre plancher, alors ne le cassez pas."](/assets/2023/03/2023-03-08-stupeur-et-tremblements/plafond-de-verre2.jpeg)
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Demander dix fois plus de compétances et pinailler sur la moindre chose pour éviter de donner une promotion à une femme ?
```suggestion
Demander dix fois plus de compétences et pinailler sur la moindre chose pour éviter de donner une promotion à une femme ?
```

2023-02-24 09:15 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Trouverais-je un jour ma place dans cette industrie qui, au fond, ne souhaite pas vraiment mon succès ?
```suggestion
Trouverai-je un jour ma place dans cette industrie qui, au fond, ne souhaite pas vraiment mon succès ?
```

2023-02-24 09:24 UTC, aHenryJard commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +# Trouverais-je un jour ma place dans cette industrie qui, au fond, ne souhaite pas vraiment mon succès ?
```suggestion
# Trouverai-je un jour ma place dans cette industrie qui, au fond, ne souhaite pas vraiment mon succès ?
```

2023-02-24 09:25 UTC, aHenryJard commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +- Demander dix fois plus de compétances et pinailler sur la moindre chose pour éviter de donner une promotion à une femme ?
```suggestion
- Demander dix fois plus de compétences et pinailler sur la moindre chose pour éviter de donner une promotion à une femme ?
```

2023-02-24 09:26 UTC, aHenryJard commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +> **Note de la Core Team Duchess**: La personne qui a écrit ce blog a  souhaité le faire de façon anonyme, nous nous sommes attachées à retirer  les éléments permettant d’identifier d’une façon ou d’
```suggestion
> **Note de la Core Team Duchess**: La personne qui a écrit ce billet a souhaité le faire de façon anonyme, nous nous sommes attachées à retirer les éléments permettant d’identifier d’une façon ou d’une autre la  personne. Si vous pensez reconnaître la personne, nous vous serions reconnaissantes de garder cette information pour vous.
```

2023-02-24 10:20 UTC, mbouquet77 commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +- “Ne pas le sentir” mais sans vraiment de raisons factuelle ?
```suggestion
- “Ne pas le sentir” mais sans vraiment de raisons factuelles ?
```

2023-02-27 09:50 UTC, MarionJS reviewed
Suggesting some spellchecking

2023-02-27 09:50 UTC, MarionJS commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Mais alors, que s’est il passé ? **J’essaye tant bien que mal d’avoir une carrière technique: voilà ce qui s’est passé.**
```suggestion
Mais alors, que s’est il passé ? **J’essaie tant bien que mal d’avoir une carrière technique: voilà ce qui s’est passé.**
```

2023-02-27 09:50 UTC, MarionJS commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Donc des hommes qui ne méritent pas la promotion l’ont, et moi pour qui on est incapable de me dire ce qu’il manque je l’ai pas ?
```suggestion
Donc des hommes qui ne méritent pas la promotion l’ont, et moi pour qui on est incapable de me dire ce qu’il manque je ne l’ai pas ?
```

2023-02-27 09:50 UTC, MarionJS commented on docs/_posts/2023/2023-03-08-stupeur-et-trembements.md
> +Mission impossible: il ne me manque rien mais j’ai pas ce qu’il faut.
```suggestion
Mission impossible: il ne me manque rien mais je n’ai pas ce qu’il faut.
```

2023-03-06 07:10 UTC, merged