Migration des posts wordpress
DuchessFrance/DuchessFrance.github.io pull request #35
Opened 2022-03-17 00:56 UTC by Pompette

2022-03-17 13:51 UTC, zbendhiba requested changes
Il y a je pense pas mal de fichier .DS_STORE à virer. Et à voir s'il y a pas d'autres types de fichiers liés à une IDE ou quoi
On doit rajouter un .gitignore

2022-03-17 13:52 UTC, zbendhiba commented
> Il y a je pense pas mal de fichier .DS_STORE à virer. Et à voir s'il y a pas d'autres types de fichiers liés à une IDE ou quoi On doit rajouter un .gitignore

Dis-moi si tu as besoin que j'en crée un ?

2022-03-17 17:19 UTC, Pompette commented
> > Il y a je pense pas mal de fichier .DS_STORE à virer. Et à voir s'il y a pas d'autres types de fichiers liés à une IDE ou quoi On doit rajouter un .gitignore
> 
> Dis-moi si tu as besoin que j'en crée un ?

Effectivement je n'y ai pas prêté attention bien vu ! J'ai supprimé les fichiers et ajouté l'ignore au fichier .gitignore existant 👍🏽

2022-03-17 17:24 UTC, zbendhiba approved these changes

2022-03-17 19:08 UTC, aHenryJard commented
Testé en local, y a juste le lien des images qui est ko, mais à la limite on peut merge comme ça puis rattraper en bash après coup. A moins que ça soit plus facile de faire ça lors de l'import ?
![lien images](https://user-images.githubusercontent.com/3634942/158877599-fe6383b2-5f92-46c9-a820-1e766ebaebe7.png)
.

2022-03-18 07:07 UTC, aHenryJard approved these changes
Allez go !

2022-03-18 07:09 UTC, merged