Rattrapage articles publiés récemment
DuchessFrance/DuchessFrance.github.io pull request #74
Opened 2022-07-19 13:09 UTC by aHenryJard

2022-08-09 10:18 UTC, Pompette requested changes

2022-08-09 10:18 UTC, Pompette commented on docs/_posts/2022/07/2022-07-11-appelez-mon-agente.md
> +categories:
Je crois que tu as oublié de mettre la catégorie ici

2022-08-09 10:18 UTC, Pompette commented on docs/_posts/2022/07/2022-07-19-promenade-au-mixit2022.md
> +categories:
Pareil ici

2023-01-06 08:43 UTC, aHenryJard commented on docs/_posts/2022/07/2022-07-11-appelez-mon-agente.md
> +categories:
fait.

2023-01-06 08:43 UTC, aHenryJard commented on docs/_posts/2022/07/2022-07-19-promenade-au-mixit2022.md
> +categories:
fait.

2023-01-06 12:27 UTC, lJoanna commented on docs/_posts/2022/05/2022-05-27-devoxx-france-par-blandine.md
> +Vous connaissez déjà leur nom : Amazone, Google, Microsoft …
```suggestion
Vous connaissez déjà leur nom : Amazon, Google, Microsoft …
```

2023-01-06 14:43 UTC, lJoanna approved these changes

2023-01-06 14:54 UTC, merged